# Generated by Django 4.2.7 on 2025-08-01 06:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (must be positive)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Income or Expense', max_length=10)),
                ('date', models.DateTimeField(help_text='Transaction date and time')),
                ('description', models.TextField(blank=True, help_text='Optional transaction description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Transaction category', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
